#ifndef QUOTES_H
#define QUOTES_H


#include <pgmspace.h>

const char* vocab[][2] PROGMEM = {
  {"Thomas Edison", "Genius is one percent inspiration and ninety-nine percent perspiration."},
  {"Yogi Berra", "You can observe a lot just by watching."},
  {"Albert Einstein", "Imagination is more important than knowledge."},
  {"Maya Angelou", "You can’t use up creativity. The more you use, the more you have."},
  {"Steve Jobs", "Stay hungry, stay foolish."},
  {"Nelson Mandela", "It always seems impossible until it’s done."},
  {"Winston Churchill", "Success is not final, failure is not fatal."},
  {"Eleanor Roosevelt", "The future belongs to those who believe in their dreams."},
  {"Theodore Roosevelt", "Do what you can, with what you have, where you are."},
  {"Wayne Gretzky", "You miss 100% of the shots you don’t take."},
  {"Helen Keller", "Optimism is the faith that leads to achievement."},
  {"Martin Luther King Jr.", "We must accept finite disappointment, but never lose infinite hope."},
  {"Oprah Winfrey", "Turn your wounds into wisdom."},
  {"Confucius", "It does not matter how slowly you go as long as you do not stop."},
  {"Vince Lombardi", "Perfection is not attainable, but if we chase it we can catch excellence."},
  {"Amelia Earhart", "The most effective way to do it, is to do it."},
  {"Walt Disney", "The way to get started is to quit talking and begin doing."},
  {"Mahatma Gandhi", "Be the change that you wish to see in the world."},
  {"Rosa Parks", "To bring about change, you must not be afraid to take the first step."},
  {"Henry Ford", "Whether you think you can or you think you can’t, you’re right."},
  {"Anne Frank", "How wonderful it is that nobody need wait a single moment before starting to improve the world."},
  {"John Lennon", "Life is what happens to you while you’re busy making other plans."},
  {"Dalai Lama", "Happiness is not something ready made. It comes from your own actions."},
  {"Marie Curie", "Nothing in life is to be feared, it is only to be understood."},
  {"Buddha", "The mind is everything. What you think you become."},
  {"Ralph Waldo Emerson", "Do not go where the path may lead, go instead where there is no path and leave a trail."},
  {"Coco Chanel", "The most courageous act is still to think for yourself. Aloud."},
  {"Abraham Lincoln", "The best way to predict your future is to create it."},
  {"J.K. Rowling", "We do not need magic to transform our world; we carry all the power we need inside ourselves already."},
  {"Malala Yousafzai", "One child, one teacher, one book, one pen can change the world."},
  {"Elon Musk", "When something is important enough, you do it even if the odds are not in your favor."},
  {"Audrey Hepburn", "Nothing is impossible, the word itself says ‘I’m possible’!"},
  {"Pablo Picasso", "Every child is an artist. The problem is how to remain an artist once he grows up."},
  {"George Bernard Shaw", "Life isn’t about finding yourself. Life is about creating yourself."},
  {"Mother Teresa", "Spread love everywhere you go. Let no one ever come to you without leaving happier."},
  {"Mark Twain", "The secret of getting ahead is getting started."},
  {"Aristotle", "We are what we repeatedly do. Excellence, then, is not an act, but a habit."},
  {"Jane Austen", "There is no charm equal to tenderness of heart."},
  {"Leonardo da Vinci", "Learning never exhausts the mind."},
  {"Serena Williams", "Every champion was once a contender that refused to give up."},
  {"William Shakespeare", "We know what we are, but know not what we may be."},
  {"Rumi", "The wound is the place where the light enters you."},
  {"Frida Kahlo", "I am my own muse, I am the subject I know best."},
  {"Neil Armstrong", "That’s one small step for man, one giant leap for mankind."},
  {"Michelle Obama", "Success isn’t about how much money you make; it’s about the difference you make in people’s lives."},
  {"Socrates", "The only true wisdom is in knowing you know nothing."},
  {"Bruce Lee", "Don’t fear failure. Not failure, but low aim, is the crime."},
  {"Ernest Hemingway", "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self."},
  {"Marilyn Monroe", "We are all of us stars, and we deserve to twinkle."},
  {"Lao Tzu", "A journey of a thousand miles begins with a single step."},
  {"Frederick Douglass", "If there is no struggle, there is no progress."},
  {"Ellen DeGeneres", "Follow your passion. Stay true to yourself."},
  {"Steve Wozniak", "Work alone. Not on a committee. Not on a team."},
  {"Virginia Woolf", "You cannot find peace by avoiding life."},
  {"Charlie Chaplin", "Life is a tragedy when seen in close-up, but a comedy in long-shot."},
  {"Simone de Beauvoir", "Change your life today. Don’t gamble on the future, act now."},
  {"Bill Gates", "Success is a lousy teacher. It seduces smart people into thinking they can’t lose."},
  {"Toni Morrison", "You are your best thing."},
  {"Nikola Tesla", "The present is theirs; the future, for which I really worked, is mine."},
  {"Harriet Tubman", "Every great dream begins with a dreamer."},
  {"John F. Kennedy", "Ask not what your country can do for you, ask what you can do for your country."},
  {"Viktor Frankl", "When we are no longer able to change a situation, we are challenged to change ourselves."},
  {"Emily Dickinson", "Hope is the thing with feathers that perches in the soul."},
  {"Thomas Jefferson", "I find that the harder I work, the more luck I seem to have."},
  {"Ada Lovelace", "Imagination is the discovering faculty, pre-eminently."},
  {"Nelson Mandela", "Education is the most powerful weapon which you can use to change the world."},
  {"Kobe Bryant", "The most important thing is to try and inspire people so that they can be great in whatever they want to do."},
  {"Oscar Wilde", "Many lack originality."},
  {"Cleopatra", "I will not be triumphed over."},
  {"Albert Schweitzer", "Do something wonderful, people may imitate it."},
  {"Dolly Parton", "If you don’t like the road you’re walking, start paving another one."},
  {"Plato", "We are twice armed if we fight with faith."},
  {"Beyoncé", "Power is not given to you. You have to take it."},
  {"Vincent van Gogh", "Great things are done by a series of small things brought together."},
  {"Stephen Hawking", "However difficult life may seem, there is always something you can do and succeed at."},
  {"Mary Shelley", "Invention, it must be humbly admitted, does not consist in creating out of void but out of chaos."},
  {"Christopher Columbus", "You can never cross the ocean until you have the courage to lose sight of the shore."},
  {"Zig Ziglar", "You don’t have to be great to start, but you have to start to be great."},
  {"Ruth Bader Ginsburg", "Real change, enduring change, happens one step at a time."},
  {"Carl Sagan", "Somewhere, something incredible is waiting to be known."},
  {"Amelia Earhart", "Adventure is worthwhile in itself."},
  {"George Eliot", "It is never too late to be what you might have been."},
  {"Hellen Keller", "The best and most beautiful things in the world cannot be seen or even touched—they must be felt with the heart."},
  {"Michael Jordan", "Talent wins games, but teamwork and intelligence win championships."},
  {"Agatha Christie", "The secret of getting ahead is getting started."},
  {"C.S. Lewis", "You are never too old to set another goal or to dream a new dream."},
  {"John Muir", "The mountains are calling and I must go."},
  {"Eleanor Roosevelt", "With the new day comes new strength and new thoughts."},
  {"Pablo Neruda", "You can cut all the flowers but you cannot keep Spring from coming."},
  {"Aesop", "No act of kindness, no matter how small, is ever wasted."},
  {"James Baldwin", "Not everything that is faced can be changed, but nothing can be changed until it is faced."},
  {"Gautama Buddha", "Peace comes from within. Do not seek it without."},
  {"Sojourner Truth", "Truth is powerful and it prevails."},
  {"Frank Lloyd Wright", "The thing always happens that you really believe in; and the belief in a thing makes it happen."},
  {"Georgia O’Keeffe", "To create one’s own world takes courage."},
  {"Desmond Tutu", "Do your little bit of good where you are; it’s those little bits of good put together that overwhelm the world."},
  {"Lucille Ball", "Love yourself first and everything else falls into line."},
  {"E.E. Cummings", "It takes courage to grow up and become who you really are."},
  {"Anais Nin", "Life shrinks or expands in proportion to one’s courage."},
  {"Peter Drucker", "The best way to predict the future is to create it."},
    {"Ben Franklin", "An investment in knowledge pays the best interest."},
  {"Kahlil Gibran", "Progress lies not in enhancing what is, but in advancing toward what will be."},
  {"Indira Gandhi", "You must learn to be still in the midst of activity."},
  {"Langston Hughes", "Hold fast to dreams, for if dreams die, life is a broken-winged bird."},
  {"Ayn Rand", "The question isn’t who is going to let me; it’s who is going to stop me."},
  {"Booker T. Washington", "Success is to be measured not by wealth but by the good one does."},
  {"Chimamanda Ngozi Adichie", "The single story creates stereotypes, and the problem with stereotypes is not that they are untrue, but that they are incomplete."},
  {"Ray Bradbury", "You don’t have to burn books to destroy a culture. Just get people to stop reading them."},
  {"Edith Wharton", "There are two ways of spreading light: to be the candle or the mirror that reflects it."},
  {"Horace Mann", "Do not think of knocking out another person’s brains because he differs in opinion from you."},
  {"Mae Jemison", "Never be limited by other people’s limited imaginations."},
  {"T.S. Eliot", "Only those who will risk going too far can possibly find out how far one can go."},
  {"Susan B. Anthony", "Independence is happiness."},
  {"Aldous Huxley", "Facts do not cease to exist because they are ignored."},
  {"Pearl S. Buck", "The young do not know enough to be prudent, and therefore they attempt the impossible, and achieve it."},
  {"Max Planck", "Science advances one funeral at a time."},
  {"Zora Neale Hurston", "Love makes your soul crawl out from its hiding place."},
  {"Herbert Spencer", "The great aim of education is not knowledge but action."},
  {"Rachel Carson", "The more clearly we can focus our attention on the wonders and realities of the universe about us, the less taste we shall have for destruction."},
  {"John Dewey", "Education is not preparation for life; education is life itself."},
  {"Mary Wollstonecraft", "Strengthen the female mind by enlarging it, and there will be an end to blind obedience."},
  {"Bertrand Russell", "The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts."},
  {"Ida B. Wells", "The way to right wrongs is to turn the light of truth upon them."},
  {"George Washington Carver", "Where there is no vision, there is no hope."},
  {"W.E.B. Du Bois", "The cost of liberty is less than the price of repression."},
  {"Alan Turing", "We can only see a short distance ahead, but we can see plenty there that needs to be done."},
  {"Margaret Mead", "Never doubt that a small group of thoughtful, committed citizens can change the world."},
  {"H.G. Wells", "Adapt or perish, now as ever, is nature’s inexorable imperative."},
  {"Chinua Achebe", "Nobody can teach me who I am. You can describe parts of me, but who I am, and what I need, is something I have to find out myself."},
  {"Dorothy Parker", "The cure for boredom is curiosity. There is no cure for curiosity."},
  {"James Joyce", "Mistakes are the portals of discovery."},
  {"Bell Hooks", "Love is an action, never simply a feeling."},
  {"Galileo Galilei", "You cannot teach a man anything; you can only help him find it within himself."},
  {"Hypatia", "Reserve your right to think, for even to think wrongly is better than not to think at all."},
  {"Rosalind Franklin", "Science and everyday life cannot and should not be separated."},
  {"Jonas Salk", "Hope lies in dreams, in imagination, and in the courage of those who dare to make dreams into reality."},
  {"Simone Weil", "Attention is the rarest and purest form of generosity."},
  {"John Stuart Mill", "The only freedom which deserves the name is that of pursuing our own good in our own way."},
  {"Virginia Satir", "We must not allow other people’s limited perceptions to define us."},
  {"Antoine de Saint-Exupéry", "A goal without a plan is just a wish."},
  {"Eudora Welty", "All serious daring starts from within."},
  {"Thurgood Marshall", "In recognizing the humanity of our fellow beings, we pay ourselves the highest tribute."},
  {"Cesare Beccaria", "The fault lies not with the laws, but with the men who administer them."},
  {"Grace Hopper", "The most damaging phrase in the language is: ‘It’s always been done that way.’"},
  {"Joseph Campbell", "Follow your bliss and the universe will open doors where there were only walls."},
  {"Edmund Burke", "The only thing necessary for the triumph of evil is for good men to do nothing."},
  {"Gwendolyn Brooks", "We are each other’s harvest; we are each other’s business; we are each other’s magnitude and bond."},
  {"Carl Jung", "The shoe that fits one person pinches another; there is no recipe for living that suits all cases."},
  {"Isadora Duncan", "You were once wild here. Don’t let them tame you."},
  {"David Hume", "A wise man proportions his belief to the evidence."},
  {"Phyllis Wheatley", "In every human breast, God has implanted a principle, which we call love of freedom."},
  {"Buckminster Fuller", "You never change things by fighting the existing reality. To change something, build a new model."},
  {"Hannah Arendt", "The sad truth is that most evil is done by people who never make up their minds to be good or evil."},
  {"Shirley Chisholm", "If they don’t give you a seat at the table, bring a folding chair."},
  {"Kurt Vonnegut", "We are what we pretend to be, so we must be careful about what we pretend to be."},
  {"John Locke", "No man’s knowledge here can go beyond his experience."},
  {"Lillian Hellman", "I cannot and will not cut my conscience to fit this year’s fashions."},
  {"Paul Dirac", "In science one tries to tell people, in such a way as to be understood by everyone, something that no one ever knew before."},
  {"Octavia E. Butler", "All that you touch you change. All that you change changes you."},
  {"Reinhold Niebuhr", "Man’s capacity for justice makes democracy possible, but man’s inclination to injustice makes democracy necessary."},
  {"Flannery O’Connor", "The truth does not change according to our ability to stomach it."},
  {"Emiliano Zapata", "It is better to die on your feet than to live on your knees."},
  {"Alvin Toffler", "The illiterate of the 21st century will not be those who cannot read and write, but those who cannot learn, unlearn, and relearn."},
  {"Mary McLeod Bethune", "Without faith, nothing is possible. With it, nothing is impossible."},
  {"Barack Obama", "Change will not come if we wait for some other person or some other time."},
  {"Wangari Maathai", "It’s the little things citizens do. That’s what will make the difference."},
  {"Edward Abbey", "A patriot must always be ready to defend his country against his government."},
  {"Marianne Williamson", "Our deepest fear is not that we are inadequate. Our deepest fear is that we are powerful beyond measure."},
  {"Jean-Jacques Rousseau", "Man is born free, and everywhere he is in chains."},
  {"Niels Bohr", "An expert is a person who has made all the mistakes that can be made in a very narrow field."},
  {"E.M. Forster", "Spoon feeding in the long run teaches us nothing but the shape of the spoon."},
  {"Arundhati Roy", "Another world is not only possible, she is on her way. On a quiet day, I can hear her breathing."},
  {"Rigoberta Menchú", "Peace cannot exist without justice, justice cannot exist without fairness."},
  {"Will Rogers", "Do the best you can, and don’t take life too serious."},
  {"Margaret Atwood", "A word after a word after a word is power."},
  {"Paulo Freire", "Education either functions as an instrument to bring about conformity or freedom."},
  {"José Martí", "The first duty of a man is to think for himself."},
  {"D.H. Lawrence", "Life is ours to be spent, not to be saved."},
  {"Ella Baker", "Give light and people will find the way."},
  {"Thomas Paine", "The mind once enlightened cannot again become dark."},
  {"Gertrude Stein", "Everybody gets so much information all day long that they lose their common sense."},
  {"Albert Camus", "Freedom is not worth having if it does not include the freedom to make mistakes."},
  {"Jawaharlal Nehru", "Life is like a game of cards. The hand you are dealt is determinism; the way you play it is free will."},
  {"Kofi Annan", "To live is to choose. But to choose well, you must know who you are."},
  {"Ursula K. Le Guin", "You cannot buy the revolution. You cannot make the revolution. You can only be the revolution."},
  {"John Greenleaf Whittier", "For all sad words of tongue and pen, the saddest are these, ‘It might have been.’"},
  {"Sylvia Plath", "The silence depressed me. It wasn’t the silence of silence. It was my own silence."},
  {"Che Guevara", "We cannot be sure of having something to live for unless we are willing to die for it."},
  {"Mikhail Gorbachev", "If what you have done yesterday still looks big to you, you haven’t done much today."},
  {"Clarissa Pinkola Estés", "The doors to the world of the wild self are few but precious."},
  {"Frederick Nietzsche", "That which does not kill us makes us stronger."},
  {"Willa Cather", "The heart of another is a dark forest, always, no matter how close it has been to one’s own."},
  {"Václav Havel", "Hope is not the conviction that something will turn out well, but the certainty that something makes sense."},
  {"Angela Davis", "You have to act as if it were possible to radically transform the world. And you have to do it all the time."},
  {"Gabriel García Márquez", "No medicine cures what happiness cannot."},
  {"Aesop", "We hang the petty thieves and appoint the great ones to public office."},
  {"Cornel West", "Justice is what love looks like in public."},
  {"Erich Fromm", "Creativity requires the courage to let go of certainties."},
  {"Terence McKenna", "You are an explorer, and you represent our species, and the greatest good you can do is to bring back a new idea."},
  {"Yayoi Kusama", "My life is a dot lost among thousands of other dots."},
    {"Epictetus", "You have power over your mind - not outside events. Realize this, and you will find strength."},
  {"Madeleine L’Engle", "You have to write the book that wants to be written."},
  {"Cesar Chavez", "Preservation of one’s own culture does not require contempt or disrespect for other cultures."},
  {"J.R.R. Tolkien", "Not all those who wander are lost."},
  {"Hedy Lamarr", "Any girl can be glamorous. All you have to do is stand still and look stupid."},
  {"Ralph Ellison", "When I discover who I am, I’ll be free."},
  {"Voltaire", "Judge a man by his questions rather than by his answers."},
  {"Toni Cade Bambara", "The role of the artist is to make the revolution irresistible."},
  {"Ibn Rushd", "Ignorance leads to fear, fear leads to hatred, and hatred leads to violence."},
  {"Sally Ride", "All adventures, especially into new territory, are scary."},
  {"Groucho Marx", "I refuse to join any club that would have me as a member."},
  {"Sappho", "What cannot be said will be wept."},
  {"Emile Zola", "If you ask me what I came into this life to do, I will tell you: I came to live out loud."},
  {"Wole Soyinka", "The greatest threat to freedom is the absence of criticism."},
  {"Condoleezza Rice", "The essence of America lies in its promise that every individual has a chance to rise."},
  {"Immanuel Kant", "We are not rich by what we possess but by what we can do without."},
  {"Lorde", "Your silence will not protect you."},
  {"Edwin Hubble", "The universe is not only stranger than we imagine, it is stranger than we can imagine."},
  {"Nadine Gordimer", "The truth isn’t always beauty, but the hunger for it is."},
  {"Thomas Malthus", "The power of population is indefinitely greater than the power in the earth to produce subsistence."},
  {"Pina Bausch", "Dance, dance, otherwise we are lost."},
  {"Chief Seattle", "Humankind has not woven the web of life. We are but one thread within it."},
  {"Maimonides", "Teach thy tongue to say ‘I do not know,’ and thou shalt progress."},
  {"Adrienne Rich", "When a woman tells the truth she is creating the possibility for more truth around her."},
  {"Marcus Aurelius", "The happiness of your life depends upon the quality of your thoughts."},
  {"Bessie Coleman", "The air is the only place free from prejudices."},
  {"Jean Piaget", "The principal goal of education is to create men who are capable of doing new things."},
  {"Lucretia Mott", "The world has never yet seen a truly great and virtuous nation."},
  {"Karl Popper", "We may become the makers of our fate when we have ceased to pose as its prophets."},
  {"Naguib Mahfouz", "You can tell whether a man is clever by his answers. You can tell whether a man is wise by his questions."},
  {"Marjane Satrapi", "The only thing that can save the world is the reclaiming of the awareness of the world."},
  {"Epicurus", "Do not spoil what you have by desiring what you have not."},
  {"Augusta Savage", "I was a leap year baby, and it seems like I’ve been leaping ever since."},
  {"Rainer Maria Rilke", "The only journey is the one within."},
  {"Fannie Lou Hamer", "Nobody’s free until everybody’s free."},
  {"Baruch Spinoza", "Peace is not an absence of war, it is a virtue, a state of mind, a disposition for benevolence."},
  {"Lydia Maria Child", "The cure for all the ills and wrongs, the cares, the sorrows, and the crimes of humanity, all lie in the one word ‘love’."},
  {"Milton Friedman", "The only way that has ever been discovered to have a lot of people cooperate together voluntarily is through the free market."},
  {"Assata Shakur", "No one is going to give you the education you need to overthrow them."},
  {"George Orwell", "Who controls the past controls the future. Who controls the present controls the past."},
  {"Edna St. Vincent Millay", "I am glad that I paid so little attention to good advice; had I abided by it I might have been saved from some of my most valuable mistakes."},
  {"Miriam Makeba", "I look at an ant and I see myself: a native South African, endowed by nature with a strength much greater than my size."},
  {"Denis Diderot", "Man will never be free until the last king is strangled with the entrails of the last priest."},
  {"Patricia Hill Collins", "Oppression is not simply a matter of individual prejudice but a systemic issue."},
  {"Heraclitus", "No man ever steps in the same river twice, for it’s not the same river and he’s not the same man."},
  {"Laverne Cox", "Each and every one of us has the capacity to be an oppressor. I want to encourage each and every one of us to interrogate how we might be an oppressor and how we might be able to become liberators."},
  {"Thorstein Veblen", "Invention is the mother of necessity."},
  {"Hilda Doolittle", "We are voyagers, discoverers of the not-known."},
  {"Kwame Nkrumah", "Freedom is not something that one people can bestow on another as a gift. They claim it as their own and none can keep it from them."},
  {"Christina Rossetti", "Better by far you should forget and smile than that you should remember and be sad."},
  {"Paul Robeson", "The artist must elect to fight for freedom or slavery. I have made my choice."},
  {"Jiddu Krishnamurti", "It is no measure of health to be well adjusted to a profoundly sick society."},
  {"Zadie Smith", "The past is always tense, the future perfect."},
  {"Bayard Rustin", "We need, in every community, a group of angelic troublemakers."},
  {"Søren Kierkegaard", "Life can only be understood backwards; but it must be lived forwards."},
  {"Gwendolyn Bennett", "I want to live dangerously, take chances, be a storm center."},
  {"Fela Kuti", "Music is the weapon of the future."},
  {"Sri Aurobindo", "The only way to make life meaningful is to make it a quest for the eternal."},
  {"Ellen Johnson Sirleaf", "If your dreams do not scare you, they are not big enough."},
  {"Max Weber", "The fate of our times is characterized by rationalization and intellectualization."},
  {"Audre Lorde", "I am not free while any woman is unfree, even when her shackles are very different from my own."},
  {"Omar Khayyam", "Be happy for this moment. This moment is your life."},
  {"Emma Goldman", "If I can’t dance, I don’t want to be part of your revolution."},
  {"Chien-Shiung Wu", "I wonder if the world would be different if we all dared to dream bigger."},
  {"Frantz Fanon", "Each generation must discover its mission, fulfill it or betray it."},
  {"June Jordan", "We are the ones we have been waiting for."},
  {"Gustave Flaubert", "There is no truth. There is only perception."},
  {" bell hooks", "The function of souls is to help one another. This is the beginning of love."},
  {"Thomas Kuhn", "Normal science does not aim at novelties of fact or theory and, when successful, finds none."},
  {"Mae West", "You only live once, but if you do it right, once is enough."},
  {"Subrahmanyan Chandrasekhar", "The black holes of nature are the most perfect macroscopic objects there are in the universe."},
  {"Fatima Mernissi", "Dignity is to have a dream, a strong one, which gives you a vision, a world where you have a place."},
  {"Countee Cullen", "Yet do I marvel at this curious thing: to make a poet black, and bid him sing!"},
  {"Simone Weil", "All sins are attempts to fill voids."},
  {"José Rizal", "He who does not know how to look back at where he came from will never get to his destination."},
  {"Vandana Shiva", "You are not Atlas carrying the world on your shoulder. It is good to remember that the planet is carrying you."},
  {"Langston Hughes", "I, too, am America."},
  {"Elie Wiesel", "The opposite of love is not hate, it’s indifference."},
  {"Martín Luther King Sr.", "You cannot hate the roots of a tree and not hate the tree."},
  {"Gloria Anzaldúa", "To survive the Borderlands you must live sin fronteras, be a crossroads."},
  {"Al-Ghazali", "Knowledge without action is wastefulness and action without knowledge is foolishness."},
  {"Beryl Markham", "I learned to wander. I learned what every dreaming child needs to know — that no horizon is so far that you cannot get above it or beyond it."},
  {"Ngũgĩ wa Thiong’o", "Our language is our soul; if we lose it, we lose ourselves."},
  {"Aphra Behn", "Love ceases to be a pleasure when it ceases to be a secret."},
  {"Eugene V. Debs", "While there is a lower class, I am in it; while there is a criminal element, I am of it."},
  {"Amartya Sen", "Development is not just about income; it is about expanding human freedoms."},
  {"Gina Rodriguez", "Your dreams are valid, no matter where you come from."},
  {"Tetsuko Kuroyanagi", "Having eyes, but not seeing beauty; having ears, but not hearing music; having minds, but not perceiving truth."},
  {"Federico García Lorca", "To burn with desire and keep quiet about it is the greatest punishment we can bring on ourselves."},
  {"Clarice Lispector", "I only achieve simplicity with enormous effort."},
  {"Walt Whitman", "Keep your face always toward the sunshine—and shadows will fall behind you."},
  {"Rigveda", "Let noble thoughts come to us from every side."},
  {"Aimé Césaire", "A civilization that proves incapable of solving the problems it creates is a decadent civilization."},
  {"Yukio Mishima", "True beauty is something that attacks, overpowers, robs, and finally destroys."},
  {"Rabindranath Tagore", "You can’t cross the sea merely by standing and staring at the water."},
  {"Sarojini Naidu", "We want deeper sincerity of motive, a greater courage in speech and earnestness in action."},
  {"Ali ibn Abi Talib", "Do not let your difficulties fill you with anxiety; it is only in the darkest nights that the stars shine more brilliantly."},
  {"Zitkala-Ša", "The voice of the Great Spirit is heard in the twittering of birds, the rippling of mighty waters, and the sweet breathing of flowers."},
    {"Soichiro Honda", "Success is 99 percent failure."},
  {"Muriel Rukeyser", "The universe is made of stories, not of atoms."},
  {"Hazrat Inayat Khan", "The soul is covered by a thousand veils."},
  {"Paul Gauguin", "I shut my eyes in order to see."},
  {"Nannie Helen Burroughs", "We specialize in the wholly impossible."},
  {"E.B. White", "I arise in the morning torn between a desire to improve the world and a desire to enjoy the world."},
  {"Mozi", "Those who love others will be loved in return."},
  {"Gina Torres", "You are enough. You are so enough, it is unbelievable how enough you are."},
  {"Alfred North Whitehead", "The art of progress is to preserve order amid change and to preserve change amid order."},
  {"Lillian Smith", "To believe in something not yet proved and to underwrite it with our lives: it is the only way we can leave the future open."},
  {"Nikos Kazantzakis", "I hope for nothing. I fear nothing. I am free."},
  {"Mary Oliver", "Tell me, what is it you plan to do with your one wild and precious life?"},
  {"Savitribai Phule", "Awaken, arise, and educate, smash traditions—liberate!"},
  {"Otto von Bismarck", "Only a fool learns from his own mistakes. The wise man learns from the mistakes of others."},
  {"Loretta Lynn", "You either have to be first, best, or different."},
  {"Mencius", "The great man is he who does not lose his child’s-heart."},
  {"Tracee Ellis Ross", "I am learning every day to allow the space between where I am and where I want to be to inspire me and not terrify me."},
  {"George Santayana", "Those who cannot remember the past are condemned to repeat it."},
  {"Nelly Sachs", "We, the rescued, beg you: show us your sun, but gradually."},
  {"Miyamoto Musashi", "You must understand that there is more than one path to the top of the mountain."},
  {"Septima Clark", "I have a great belief in the fact that whenever there is chaos, it creates wonderful thinking."},
  {"Adam Smith", "The real tragedy of the poor is the poverty of their aspirations."},
  {"Lucille Clifton", "We are running out of time, but not out of love."},
  {"Dogen", "If you cannot find the truth right where you are, where else do you expect to find it?"},
  {"Lila Watson", "If you have come to help me, you are wasting your time. But if you have come because your liberation is bound up with mine, then let us work together."},
  {"Matthew Arnold", "Resolve to be thyself; and know that he who finds himself, loses his misery."},
  {"Marva Collins", "Success doesn’t come to you, you go to it."},
  {"Ibn Khaldun", "The past resembles the future more than one drop of water resembles another."},
  {"Patsy Mink", "We have to build things that we want to see accomplished, in life and in our country."},
  {"Edwin Markham", "There is a destiny that makes us brothers; none goes his way alone."},
  {"B.K.S. Iyengar", "Change is not something that we should fear. Rather, it is something that we should welcome."},
  {"Lillian Gish", "A good enemy is a better person than a false friend."},
  {"Sri Chinmoy", "Judge nothing, you will be happy. Forgive everything, you will be happier."},
  {"Etty Hillesum", "Ultimately, we have just one moral duty: to reclaim large areas of peace in ourselves."},
  {"Shirley Jackson", "No live organism can continue for long to exist sanely under conditions of absolute reality."},
  {"Alphonse de Lamartine", "To love for the sake of being loved is human, but to love for the sake of loving is angelic."},
  {"Daisaku Ikeda", "A great human revolution in just a single individual will help achieve a change in the destiny of a nation."},
  {"Zaha Hadid", "Architecture is really about well-being."},
  {"Ovid", "Let your hook be always cast; in the pool where you least expect it, there will be a fish."},
  {"Mamphela Ramphele", "The only way to change the world is to change the way we live in it."},
  {"Mahmoud Darwish", "We are captives of what we love, what we desire, and what we are."},
  {"Baha’u’llah", "So powerful is the light of unity that it can illuminate the whole earth."},
  {"Lisel Mueller", "When I am asked how I began writing poems, I talk about the indifference of nature."},
  {"Haim Ginott", "I have come to the frightening conclusion that I am the decisive element."},
  {"Mary Harris Jones", "Pray for the dead and fight like hell for the living."},
  {"Ananda Coomaraswamy", "The artist is not a special kind of person; rather each person is a special kind of artist."},
  {"Tenzin Gyatso", "If you think you are too small to make a difference, try sleeping with a mosquito."},
  {"Phillis Wheatley", "Through thickest gloom look back, immortal shade, on that confusion which thy death has made."},
  {"Protagoras", "Man is the measure of all things."},
  {"Nusrat Fateh Ali Khan", "Music is the language of the heart; it speaks where words fail."},
  {"Eleanor Holmes Norton", "The only way to make sure people you agree with can speak is to support the rights of people you don’t agree with."},
  {"Sri Ramakrishna", "The winds of grace are always blowing, but you have to raise the sail."},
  {"Rita Dove", "You have to imagine it possible before you can see something."},
  {"Avicenna", "The knowledge of anything, since all things have causes, is not acquired or complete unless it is known by its causes."},
  {"Winona LaDuke", "The essence of the problem is about consumption, recognizing that a society that consumes one-third of the world’s resources is unsustainable."},
  {"Herman Hesse", "Some of us think holding on makes us strong, but sometimes it is letting go."},
  {"Nizar Qabbani", "In the summer, I stretch out on the shore and think of you."},
  {"Dorothy Height", "Greatness is not measured by what a man or woman accomplishes, but by the opposition he or she has overcome."},
  {"Paracelsus", "The art of healing comes from nature, not from the physician."},
  {"Ama Ata Aidoo", "People are worms, and even the God who created them is immensely bored with their antics."},
  {"George Mason", "All men are by nature equally free and independent."},
  {"Shirin Ebadi", "Human rights are not a luxury, they are a necessity."},
  {"Meister Eckhart", "The eye through which I see God is the same eye through which God sees me."},
  {"Betsy Mix Cowles", "Equal justice to all is the only safe foundation for any government."},
  {"T’ao Ch’ien", "I live in peace with the universe, my spirit free as the wind."},
  {"Homi K. Bhabha", "The margins of the text are never marginal to the meaning."},
  {"Toyo Ito", "Architecture is about creating spaces that evoke human emotions."},
  {"Elizabeth Blackwell", "For what is done or learned by one class of women becomes, by virtue of their common womanhood, the property of all women."},
  {"Allama Iqbal", "Nations are born in the hearts of poets, they prosper and die in the hands of politicians."},
  {"Luo Guanzhong", "It is better to be the leader of a small group than the follower of a large one."},
  {"Maryam Mirzakhani", "The beauty of mathematics only shows itself to more patient followers."},
  {"Mira Nair", "Never treat anything you do as a stepping stone. Do it fully, and follow it completely."},
  {"Menander", "He who labors diligently need never despair."},
  {"Ruby Bridges", "Don’t follow the path. Go where there is no path and begin the trail."},
  {"Jalāl ad-Dīn Rūmī", "Out beyond ideas of wrongdoing and rightdoing, there is a field. I’ll meet you there."},
  {"Lillian Wald", "The task of organizing human happiness is the greatest challenge of our age."},
  {"Alvar Aalto", "Form must have a content, and that content must be linked with nature."},
  {"Sholem Aleichem", "Life is a dream for the wise, a game for the fool, a comedy for the rich, a tragedy for the poor."},
  {"Grace Lee Boggs", "We are not just here to resist. We are here to create a new world."},
  {"Anaxagoras", "Everything has a natural explanation. The moon is not a god, but a great rock."},
  {"Phan Thi Kim Phuc", "Forgiveness made me free from hatred. I still have many scars on my body and severe pain most days but my heart is cleansed."},
  {"Bede", "The life of man is of no greater duration than the breath of his nostrils."},
  {"Toni Cade Bambara", "Revolution begins with the self, in the self."},
  {"Le Corbusier", "To create architecture is to put in order. Put what in order? Function and objects."},
  {"Huda Sha’arawi", "Men have singled out women of outstanding merit and put them on a pedestal to avoid recognizing the capabilities of all women."},
  {"Matsuo Basho", "Do not seek to follow in the footsteps of the wise. Seek what they sought."},
  {"Faiz Ahmed Faiz", "Speak, your lips are free. Speak, it is your own tongue."},
  {"Jigme Singye Wangchuck", "Gross National Happiness is more important than Gross National Product."},
  {"Katherine Johnson", "I don’t worry about people’s opinions. I just do my job."},
  {"Olaudah Equiano", "The life of man is uncertain, and his days are few."},
  {"Tawakkol Karman", "Peace does not mean just to stop wars, but also to stop oppression and injustice."},
  {"Edvard Munch", "From my rotting body, flowers shall grow and I am in them, and that is eternity."},
  {"Dante Alighieri", "The path to paradise begins in hell."},
  {"B.R. Ambedkar", "I measure the progress of a community by the degree of progress which women have achieved."},
  {"Annie Besant", "Better remain silent, better not even think, if you are not prepared to act."},
  {"Chandra Talpade Mohanty", "Solidarity is not a market exchange."},
  {"Tupac Shakur", "I’m not saying I’m gonna change the world, but I guarantee that I will spark the brain that will."},
  {"Zhuangzi", "Life is finite, while knowledge is infinite."},
  {"Elsa Schiaparelli", "In difficult times, fashion is always outrageous."},
  {"Sri Aurobindo", "The only way to make life meaningful is to make it a quest for the eternal."},
    {"Akhenaten", "True wisdom is less presuming than folly."},
  {"Alma Thomas", "Creative art is for all time and is therefore independent of time."},
  {"Ammar ibn Yasir", "Patience is the key to relief."},
  {"Anaïs Nin", "We don’t see things as they are, we see them as we are."},
  {"Ansel Adams", "You don’t take a photograph, you make it."},
  {"Antonin Artaud", "No one has ever written, painted, sculpted, modeled, built, or invented except literally to get out of hell."},
  {"Anwar Sadat", "Peace is much more precious than a piece of land."},
  {"Artemisia Gentileschi", "My illustrous lordship, I’ll show you what a woman can do."},
  {"Arundhati Roy", "The only thing worth globalizing is dissent."},
  {"Aryabhata", "By the grace of mathematics, the universe is understood."},
  {"Ashoka", "To do good is difficult, but it is more difficult to begin to do good."},
  {"Augusto Boal", "Theater is a weapon, and it is the people who should wield it."},
  {"Aung San Suu Kyi", "The only real prison is fear, and the only real freedom is freedom from fear."},
  {"Avvaiyar", "What you have learned is a mere handful; what you haven’t learned is the size of the world."},
  {"Baba Amte", "I sought my soul, but my soul I could not see. I sought my God, but my God eluded me. I sought my brother, and I found all three."},
  {"Ban Zhao", "Humility is the root of honor."},
  {"Barbara Jordan", "What the people want is very simple—they want an America as good as its promise."},
  {"Bessie Smith", "It’s a long old road, but I know I’m gonna find the end."},
  {"Bhagat Singh", "Revolution is an inalienable right of mankind."},
  {"Bhumibol Adulyadej", "A good person can make another person good; it means that goodness will elicit goodness in the society."},
  {"Bibi Khadija", "Wealth is not in possessions, but in giving."},
  {"Birsa Munda", "The earth is ours; we will not let it be taken."},
  {"Blaise Pascal", "The heart has its reasons which reason knows not."},
  {"Bono", "Music can change the world because it can change people."},
  {"C.P. Cavafy", "You won’t find a new country, won’t find another shore. This city will always pursue you."},
  {"Carmen Miranda", "I’ve got a marvelous future ahead, and I’m not afraid of it."},
  {"Catherine the Great", "I praise loudly, I blame softly."},
  {"Cesária Évora", "The sea has no roads, the sea is free."},
  {"Chanakya", "A person should not be too honest. Straight trees are cut first."},
  {"Charlemagne", "To have another language is to possess a second soul."},
  {"Charlotte Brontë", "I am no bird; and no net ensnares me."},
  {"Chimamanda Ngozi Adichie", "We should all be feminists."},
  {"Chinua Achebe", "Until the lions have their own historians, the history of the hunt will always glorify the hunter."},
  {"Chögyam Trungpa", "The path is the goal."},
  {"Claude Monet", "I must have flowers, always, and always."},
  {"Cleopatra VII", "My honor was not yielded, but conquered."},
  {"Confucius", "The man who moves a mountain begins by carrying away small stones."},
  {"Constantine Cavafy", "When you set out for Ithaca, ask that your way be long."},
  {"Coretta Scott King", "Freedom and justice cannot be parceled out in pieces to suit political convenience."},
  {"Cornelia Funke", "Stories never really end, even if the books like to pretend they do."},
  {"Czesław Miłosz", "Not that I want to be a god or a hero. Just to change into a tree, grow for ages, not hurt anyone."},
  {"D.T. Suzuki", "Zen teaches nothing; it merely enables us to wake up and become aware."},
  {"Dante Alighieri", "Follow your own star!"},
  {"David Bowie", "Tomorrow belongs to those who can hear it coming."},
  {"Debbie Harry", "The only place where success comes before work is in the dictionary."},
  {"Democritus", "Happiness resides not in possessions, and not in gold, happiness dwells in the soul."},
  {"Derek Walcott", "The time will come when, with elation, you will greet yourself arriving at your own door."},
  {"Desiderius Erasmus", "In the country of the blind, the one-eyed man is king."},
  {"Dionne Warwick", "You have to learn to live with yourself before you can live with others."},
  {"Djuna Barnes", "A man is whole only when he takes into account his shadow."},
  {"Dolores Huerta", "Every moment is an organizing opportunity, every person a potential activist."},
  {"Dorothy Day", "The greatest challenge of the day is: how to bring about a revolution of the heart."},
  {"Dr. Seuss", "Why fit in when you were born to stand out?"},
  {"Dylan Thomas", "Do not go gentle into that good night."},
  {"Edith Piaf", "I want to make people cry even when they don’t understand my words."},
  {"Eduardo Galeano", "The world is not made of atoms; it’s made of stories."},
  {"Edward Said", "You cannot continue to victimize someone else just because you yourself were a victim once."},
  {"Elie Wiesel", "We must take sides. Neutrality helps the oppressor, never the victim."},
  {"Elizabeth Barrett Browning", "Light tomorrow with today!"},
  {"Elizabeth Cady Stanton", "The moment we begin to fear the opinions of others, truth is endangered."},
  {"Ellen Sirleaf", "Leadership is about making others better as a result of your presence."},
  {"Emiliano Zapata", "I’d rather die on my feet than live on my knees."},
  {"Emma Lazarus", "Give me your tired, your poor, your huddled masses yearning to breathe free."},
  {"Enheduanna", "My heart is the temple where your spirit dwells."},
  {"Enrico Fermi", "The universe is not only queerer than we suppose, but queerer than we can suppose."},
  {"Erik Erikson", "The only thing that can save us is a sense of community."},
  {"Es’kia Mphahlele", "A writer is not just a recorder of events, but a creator of meanings."},
  {"Eugene O’Neill", "Man is born broken. He lives by mending. The grace of God is glue."},
  {"Euripides", "No one can confidently say that he will still be living tomorrow."},
  {"Eva Perón", "Where there is a worker, there lies a nation."},
  {"Fannie Lou Hamer", "You can pray until you faint, but unless you get up and try to do something, God is not going to put it in your lap."},
  {"Fatima al-Fihri", "Education is the foundation of progress."},
  {"Federico Fellini", "All art is autobiographical; the pearl is the oyster’s autobiography."},
  {"Fela Kuti", "To be a revolutionary, you have to be a human being."},
  {"Fernando Pessoa", "To live is to be someone else."},
  {"Flora Nwapa", "Women are the backbone of any society, but their strength is often unseen."},
  {"Frances Ellen Watkins Harper", "We are all bound up together in one great bundle of humanity."},
  {"Francis Bacon", "Knowledge is power."},
  {"Frank Herbert", "Fear is the mind-killer."},
  {"Franz Kafka", "Start with what is right rather than what is acceptable."},
  {"Fred Rogers", "We live in a world in which we need to share responsibility."},
  {"Frida Kahlo", "Feet, what do I need you for when I have wings to fly?"},
  {"Gabriel García Márquez", "It is not true that people stop pursuing dreams because they grow old, they grow old because they stop pursuing dreams."},
  {"Gabriela Mistral", "We are guilty of many errors, but our worst crime is abandoning the children."},
  {"Gaston Bachelard", "The subconscious is ceaselessly murmuring, and it is by listening to these murmurs that one hears the truth."},
  {"George Herbert", "Do not wait; the time will never be ‘just right.’"},
  {"George R.R. Martin", "A reader lives a thousand lives before he dies."},
  {"Georgia Douglas Johnson", "Your world is as big as you make it."},
  {"Giacomo Leopardi", "Real misanthropes are not found in solitude, but in the world."},
  {"Gianni Versace", "Don’t be into trends. Don’t make fashion own you."},
  {"Gilles Deleuze", "A concept is a brick. It can be used to build a courthouse of reason. Or it can be thrown through the window."},
  {"Gina Lollobrigida", "A woman at 20 is like ice, at 30 she is warm, and at 40 she is hot."},
  {"Gwendolyn Brooks", "Poetry is life distilled."},
  {"H.D. (Hilda Doolittle)", "At least I have the flowers of myself, and my thoughts, no god can take that."},
  {"Haile Selassie", "Throughout history, it has been the inaction of those who could have acted that has made it possible for evil to triumph."},
  {"Haim Ginott", "I’ve come to the frightening conclusion that I am the decisive element in the classroom."},
  {"Hannah Senesh", "There are stars whose radiance is visible on Earth though they have long been extinct."},
  {"Harriet Beecher Stowe", "Never give up, for that is just the place and time that the tide will turn."},
  {"Hassan Fathy", "Architecture is the art of building for the human spirit."},
  {"Hector Berlioz", "Time is a great teacher, but unfortunately it kills all its pupils."},
  {"Henry David Thoreau", "Go confidently in the direction of your dreams. Live the life you have imagined."},
  {"Henry James", "Three things in human life are important: the first is to be kind; the second is to be kind; and the third is to be kind."},
  {"Hesiod", "Badness you can get easily, in quantity; the road is smooth, and it lies close by."},
  {"Hillary Clinton", "You don’t have to be perfect, but you do have to be persistent."},
  {"Ho Chi Minh", "Nothing is more precious than independence and liberty."},
  {"Homer", "There is a time for many words, and there is also a time for sleep."},
  {"Horace", "Seize the day, put no trust in the morrow!"},
  {"Howard Zinn", "You can’t be neutral on a moving train."},
  {"Huda Sha’arawi", "To be free, one must first be aware."},
  {"Hugh Masekela", "Music is a universal language that transcends all boundaries."},
  {"Hussein of Jordan", "The sky is not the limit; the mind is."},
  {"Hypatia of Alexandria", "All formal dogmatic religions are fallacious and must never be accepted by self-respecting persons as final."},
  {"Ibn Battuta", "Traveling—it leaves you speechless, then turns you into a storyteller."},
  {"Ibn Sina", "The world is a garden, whose gardener is the human soul."},
  {"Ida Tarbell", "Imagination is the only key to the future. Without it none exists."},
  {"Igor Stravinsky", "I have learned throughout my life as a composer chiefly through my mistakes."},
  {"Imhotep", "Build with the future in mind, for what you create will outlast you."},
  {"Indira Gandhi", "You cannot shake hands with a clenched fist."},
  {"Isak Dinesen", "The cure for anything is salt water: sweat, tears, or the sea."},
  {"Ismail Kadare", "Literature is the only thing that makes life bearable."},
  {"Ivan Turgenev", "If we wait for the moment when everything is ready, we shall never begin."},
  {"Jack Kerouac", "The only truth is music."},
  {"James Baldwin", "You have to go the way your blood beats."},
  {"James Joyce", "Your battles inspired me—not the obvious material battles but those that were fought and won behind your forehead."},
  {"Jane Goodall", "What you do makes a difference, and you have to decide what kind of difference you want to make."},
  {"Jean Cocteau", "Art is a marriage of the conscious and the unconscious."},
  {"Jeanette Winterson", "You don’t fall in love with someone because it’s convenient."},
  {"Jens Stoltenberg", "The best way to ensure peace is to be strong enough to defend it."},
  {"Jessica Tandy", "You can’t just sit there and wait for people to give you that golden dream."},
  {"Joaquín Rodrigo", "Music is the poetry of the air."},
  {"Jody Williams", "Emotion without action is irrelevant."},
  {"Johann Wolfgang von Goethe", "Whatever you can do or dream you can, begin it. Boldness has genius, power, and magic in it."},
  {"John Coltrane", "My music is the spiritual expression of what I am."},
  {"John Donne", "No man is an island, entire of itself."},
  {"John Keats", "Beauty is truth, truth beauty—that is all ye know on earth, and all ye need to know."},
  {"John Lewis", "You are a light. You are the light. Never let anyone—any person or any force—dampen, dim, or diminish your light."},
  {"John Milton", "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven."},
  {"John Muir", "In every walk with nature, one receives far more than he seeks."},
  {"Jonas Salk", "The reward for work well done is the opportunity to do more."},
  {"Jorge Luis Borges", "I have always imagined that Paradise will be a kind of library."},
  {"José Martí", "Liberty is the right of every man to be honest."},
  {"Josephine Baker", "To realize our dreams we must decide to wake up."},
  {"Jules Verne", "We may brave human laws, but we cannot resist natural ones."},
  {"Julia Child", "Find something you’re passionate about and keep tremendously interested in it."},
  {"Julian of Norwich", "All shall be well, and all shall be well, and all manner of thing shall be well."},
  {"Julio Cortázar", "We walked without looking for each other, but knowing we were walking to find each other."},
  {"June Jordan", "Poetry is a political act because it involves telling the truth."},
  {"Kahlil Gibran", "Your living is determined not so much by what life brings to you as by the attitude you bring to life."},
  {"Kalpana Chawla", "The path from dreams to success does exist. May you have the vision to find it."},
  {"Karen Blixen", "I write a little every day, without hope and without despair."},
  {"Kate Chopin", "The voice of the sea speaks to the soul."},
  {"Katherine Dunham", "Go within every day and find the inner strength so that the world will not blow your candle out."},
  {"Kenzaburō Ōe", "The only way to survive is by telling stories."},
  {"Khaled Hosseini", "It may be unfair, but what happens in a few days, sometimes even a single day, can change the course of a whole lifetime."},
  {"Khalil Gibran", "You give but little when you give of your possessions. It is when you give of yourself that you truly give."},
  {"Kim Il-sung", "The people are the masters of the revolution in each country."},
  {"Kofi Annan", "Knowledge is power. Information is liberating."},
  {"Kumari Jayawardena", "Feminism is not a Western invention; it is a global struggle."},
  {"Kurt Vonnegut", "We have to continually be jumping off cliffs and developing our wings on the way down."},
  {"L.M. Montgomery", "Isn’t it nice to think that tomorrow is a new day with no mistakes in it yet?"},
  {"Lakhdar Brahimi", "Peace is not a one-time achievement but a continuous process."},
  {"Langston Hughes", "Let the rain kiss you. Let the rain beat upon your head with silver liquid drops."},
  {"Lao Tzu", "When I let go of what I am, I become what I might be."},
  {"Laura Ingalls Wilder", "The real things haven’t changed. It is still best to be honest and truthful."},
  {"Lech Wałęsa", "We hold our heads high, despite the price we have paid, because freedom is priceless."},
  {"Lena Horne", "You have to be taught to be second class; you’re not born that way."},
  {"Leo Tolstoy", "Everyone thinks of changing the world, but no one thinks of changing himself."},
  {"Leon Trotsky", "The end may justify the means as long as there is something that justifies the end."},
  {"Leonard Bernstein", "To achieve great things, two things are needed: a plan, and not quite enough time."},
  {"Leonardo da Vinci", "It had long since come to my attention that people of accomplishment rarely sat back and let things happen to them."},
  {"Leslie Marmon Silko", "I will tell you something about stories—they aren’t just entertainment."},
  {"Li Bai", "The road is long, but my heart is longer."},
  {"Lila Tretikov", "The power of open knowledge lies in its ability to connect people."},
  {"Lillian Hellman", "People change and forget to tell each other."},
  {"Linton Kwesi Johnson", "Writing was a political act and poetry was a cultural weapon."},
  {"Lisa See", "Read a thousand books, and your words will flow like a river."},
  {"Lorca", "The poem, the song, the picture, is only water drawn from the well of the people."},
  {"Louis Armstrong", "What we play is life."},
  {"Louise Erdrich", "Life will break you. Nobody can protect you from that."},
  {"Lucille Ball", "The more things you do, the more you can do."},
  {"Lucretius", "The drops of rain make a hole in the stone, not by violence, but by oft falling."},
  {"Ludwig van Beethoven", "Music is the mediator between the spiritual and the sensual life."},
  {"Luis Buñuel", "Imagination is our only weapon in the war against reality."},
  {"Lydia Child", "Belief in oneself is one of the most important bricks in building any successful venture."},
  {"Lynn Nottage", "We are storytellers, and stories are how we make sense of the world."}
};

const int vocabSize = 583;

#endif